### ISSUE TITLE
Can't save log due to "write_results" vs "write_result"

### ISSUE THREAD

**Issue by camminady** [robertfeldt/BlackBoxOptim.jl#103]
I get an 

`ERROR: UndefVarError: write_results not defined`

When running bboptimize for a configuration with
```
 :SaveTrace      => true,
 :SaveFitnessTraceToCsv => true,
 :SaveParameters => true
```

This might be due to the fact, that there is a wrong spelling in the function definition (or call) of "write_result" (or "write_results"): 
See https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/src/opt_controller.jl
Line 450: 
` write_results(ctrl)`
vs Line 347: 
`function write_result(ctrl::OptRunController, filename = "")`
Note the difference in spelling: results vs result.

Steps to reproduce: Unzip the attachment. Start Julia (1.01):

[bbbug.zip](https://github.com/robertfeldt/BlackBoxOptim.jl/files/2542594/bbbug.zip)
```
julia> include("setup.jl");

julia> p = setup("config.json");

julia> bboptimize(p);
```
Resulting in:
```
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
DE modify state:

Optimization stopped after 5001 steps and 0.09289312362670898 seconds
Termination reason: Max number of steps (5000) reached
Steps per second = 53836.062398940514
Function evals per second = 54643.4418590326
Improvements/step = 0.7718
Total function evaluations = 5076


Best candidate found: [3.02077e-15, 0.811824, 1.74323, 1.01808, 0.147884, 0.984137, 0.380032]

Fitness: 0.000000000

ERROR: UndefVarError: write_results not defined
Stacktrace:
 [1] run!(::BlackBoxOptim.OptController{DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}},FunctionBasedProblem{ScalarFitnessScheme{true},RangePerDimSearchSpace,Nothing}}) at /home/thomas/.julia/packages/BlackBoxOptim/RgNEa/src/opt_controller.jl:430
 [2] #bboptimize#71 at /home/thomas/.julia/packages/BlackBoxOptim/RgNEa/src/bboptimize.jl:65 [inlined]
 [3] bboptimize(::BlackBoxOptim.OptController{DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}},FunctionBasedProblem{ScalarFitnessScheme{true},RangePerDimSearchSpace,Nothing}}) at /home/thomas/.julia/packages/BlackBoxOptim/RgNEa/src/bboptimize.jl:62
 [4] top-level scope at none:0
```

The whole thing should be easy to fix by correcting the typo.

**Comment by robertfeldt** [comment]
Thanks for reporting this. It does seem like an easy fix. However, I want to clean up these multiple parameters around logging and saving; seems many of them are no longer used. ;) In the mean time you can use the callback interface to save to disk as the optimization goes on. I'll try to put together an example of how to do this. Maybe this can even be the preferred way to do this rather than save the optimization history in mem as we do now.

**Comment by robertfeldt** [comment]
Please check if this example helps you in saving fitness progress during optimization:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/save_fitness_progress_via_callback_function.jl

Longer-term we probably want to take away the different tracing options and let people implement this themselves via the callback interface instead. It can handle many different situations rather than adding a lot of different parameters...

**Comment by robertfeldt** [comment]
Fixed by:

https://github.com/robertfeldt/BlackBoxOptim.jl/commit/e1e3ed0e0506aba59b43ab3fd90430ce0f7df147
