### ISSUE TITLE
Fitness history per function evaluation

### ISSUE THREAD

**Issue by MrUrq** [robertfeldt/BlackBoxOptim.jl#110]
Hi, 

Is it possible to obtain the fitness history of the best individual as a function of the current number of function evaluations? I am aware of `CallbackFunction` and `CallbackInterval` however it seems like this isn't what I'm looking for. 

The best I've got so far is: 
```
function rosenbrock2d(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

sol_hist = Array{Float64,1}()
f_c = x->push!(sol_hist,rosenbrock2d(best_candidate(x)))
res = bboptimize(rosenbrock2d;SearchRange=(-5.0,5.0), NumDimensions = 2, PopulationSize=10, MaxFuncEvals=100, CallbackFunction = f_c,CallbackInterval = eps());
```
The length of `sol_hist` varies if you re-run the example and it's not clear to me how each element of `sol_hist` is related to the current number of function evaluations. Ideally  the length of `length(sol_hist) = MaxFuncEvals` or maybe `length(sol_hist) = MaxFuncEvals/PopulationSize`, whichever makes more sense. 

Additionally it could be useful to set `CallbackInterval` as an `Int` representing the number of generations or number of function evaluations to execute before invoking `CallbackFunction`. 

Thanks for a great package!

**Comment by robertfeldt** [comment]
Thanks for your feedback! You can get the current number of function evaluations from the controller object sent to the callback function although it is not yet exported. CallbackFunction is still not perfect since it is based on time but maybe this is close enough to your needs, at least for now:

```julia
function rosenbrock2d(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

sol_hist = Array{Tuple{Int, Float64},1}()
f_c = oc -> push!(sol_hist, (num_func_evals(oc), best_fitness(oc)))

res = bboptimize(rosenbrock2d;SearchRange=(-5.0,5.0), NumDimensions = 2, PopulationSize=10, MaxFuncEvals=100, CallbackFunction = f_c,CallbackInterval = -1.0);
```

Note that it is better to get the current best fitness via `best_fitness` since your version needs to call the function being optimized (which might be costly).

Using an Int is not perfect since different optimization algorithms might need more than 1 function evaluation per step. Many do only one func eval per step but some take more. Maybe we could callback at every step if the callback interval was set to zero or negative?

**Comment by robertfeldt** [comment]
I have now made the change and the commits are on the Master branch. I also added example code here, based on your example:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/save_fitness_progress_via_callback_function.jl

Closing this...
