### ISSUE TITLE
Does the NES algorithm really support different population sizes?

### ISSUE THREAD

**Issue by zxjroger** [robertfeldt/BlackBoxOptim.jl#148]
Hi, thank you for this amazing package. I am testing NES algorithms in your package to minimize a function, namely, `:xnes`, `:dxnes`, and `:separable_nes`. I set population size in the `bboptimize( )` function by `PopulationSize = N`. I find that no matter how I change the population size, I always got the same solution and I know the solution is not the correct solution. However, when I change the population size for say `:adaptive_de_rand_1_bin_radiuslimited` algorithm, the solutions do change with population sizes. Therefore, I wonder if there is another way to set population size for NES algorithms? Thank you.

**Comment by robertfeldt** [comment]
Thanks for the feedback!
Yeah, it can be a bit confusing that the top-level api (`bboptimize`) does not separate between parameters for different optimization methods. So each method has their own set of parameters and they are not named in a common way but rather in relation to each algorithm. For the NES family of algorithms there isn't really a population size since the population is characterized by a current/mean value and a covariance matrix. But there is a parameter called `lambda` that governs how many samples are sampled per update of the matrix. It is not really recommended to play with that for the NES family but you can if you want to. Please check the file:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/src/natural_evolution_strategies.jl

to see parameters of each algorithm.

Longer-term we should probably have algorithm-specific objects that are setup before calling bboptimize rather than selecting the algorithm in the call itself. 

Hope this helps!

**Comment by zxjroger** [comment]
Hi, thanks for the answer. I am not really familiar with all the algorithms. For NES family, when you say 
> It is not really recommended to play with that for the NES family but you can if you want to. 

Is it because the default value of `lambda` is almost always the best or is it because the solution may not change with respect to `lambda`?

**Comment by robertfeldt** [comment]
If I remember correctly the default setting for lambda was based on extensive experimentation by the authors so I do think there is quite some evidence to stay with the default.

But actually, I'm not convinced that our full NES alg version is really stable and solid; it has not consistently given me the kind of results I expect. Also it is often a problem that it does not adhere to box constraints. I suggest trying the DE family and only go for NES if DE is not helping on your problem. Quite soon I plan to update with some recent CMA-ES algorithm(s) that have shown very good results on a broad set of problems. That might be a good alternative to try then.

Hope this helps!

**Comment by zxjroger** [comment]
I see, thank you very much. I actually find XNES to be a good fit to my problem.

I also tried the recommended `adaptive_de_rand_1_bin_radiuslimited` algorithm. But the performance is not that good. I tested it with 5 population sizes: 50, 100, 150, 200, 250. It only finds the optimal solution with population size of 50.

**Comment by robertfeldt** [comment]
Interesting, this is quite rare for me on my problems.

When it comes to DE there is a trade-off. With larger population sizes you need to give it more time since it "starts broader" and thus spends more time before it "focuses" on the most promising areas. The benefit is that it is less likely to miss important areas. But of course, it depends on the problem at hand etc. and YMMV. On high-dimensional problems I find DE to be quite robust. But I have high hopes for recent CMA-ES variants which can trade-off between being very fast on simpler (more separable) problems while still being effective on problems with more complex dependence structures. Also, you might try running NelderMead or something basic on the final output of DE since it can sometimes have troubles going the "last mile". You can check here for results showing DE+NelderMead performance as good on a wide range of problems: 
https://github.com/jonathanBieler/BlackBoxOptimizationBenchmarking.jl

**Comment by zxjroger** [comment]
Thanks for the suggestion. I will give it a try. I really look forward to the CMA-ES algorithm.
