### ISSUE TITLE
SearchRange - Question

### ISSUE THREAD

**Issue by gacarita** [robertfeldt/BlackBoxOptim.jl#196]
Hello

i've been running few tests with BlackBoxOptim and i've not seen anything related with conservative search range. I would like to work with something like A + B + C = 1 and at everystep this relationship need to be respect. Is there any way to do this now?

**Comment by robertfeldt** [comment]
There is no general way to support any type of constraint but the general idea would be to do it by heavily penalizing solutions that don't fulfill the constraints. There is quite a large literature on this and I suggest you check it out but to give you a more hands-on example for your case a starting point can be something like below...

The first thing is to try to simplify/reduce the degrees of freedom so that there is some help to the optimizer in fulfilling the constraint already in how you setup the problem. Here for example, if you optimize only the values of A and B then C would be determined by the values of A and B like so: C = 1 - A - B. So maybe you can search only for values of A and B and then let C be determined by this equation? If so, then you can guarantee the constraint is fulfilled.

However, this might not always be possible or it does not work well together with range constraints for the variables, i.e. you risk not exploring all possible values of the ranges. Assume the original fitness function being optimized is `origfit` with a max value (or at least a max bound) called OF_MAX, then you can create a penalized fitness function something like so:

```julia
penalizedfitness(X) = 10*OF_MAX*constraint_penalty(X) + origfit(X)
function constraint_penalty(X)
   A,B,C = X
   abs((A+B+C) - 1) # Will be zero when constraint satisfied or positive and larger the further away from constraint we are
end
```

Now by optimizing `penalizedfitness` instead of `origfit` there is such a large penalty for being far away from the fulfilling the constraint that the optimizer will have to try to both fulfill the constraint while minimizing the original fitness. However, depending on the problem this might be very hard and the penalization might hurt the optimization so YMMV.

Combining the two approaches above might also be worth exploring, as well as using multi-objective optimization where one objective is origfit and one the the penalization for violating the constraint. It might also be helpful to consider some small delta value of distance from constraint fulfilment that you allow to make the "area" of the search space that is viable larger. This can help the optimization and once you have a good set of solutions to start from you can then find the closest one that exactly fulfills the constraint.

I hope this helps.

**Comment by gacarita** [comment]
Hey Robert. Thank you for the quick response.

I'm trying to think about reduce my deegres of freedom because my bounds needs to be inside a irregular shape, which is given by ellipsoid and i'm considering n-points, so each point has A,B,C coordinates to be optimized( especific minimize) and i need to check out every single point for the conditions (deegres of freedom n_points*3).  The method you suggest `penalizedfitness(X) = 10*OF_MAX*constraint_penalty(X) + origfit(X)` is working fine for 1,2,3,4,5 points (tested with 5 points at max). I'm using the average value of the `constraint_penalty` and i'm pretty sure that's not the best way to do that but it's the best i've figure out at this point (i think that should not work when i highly increases the number of points because no bounded values should be diluted in my average values). 

Could you share some references ? I'm interested to learn more about the constraints methods and optimization methods.

**Comment by robertfeldt** [comment]
This is a bit dated and not detailed but gives an overview of some early methods (and you can check on Google Scholar who cites this paper since it's been around for long and is heavily cited):

Yeniay, Özgür. "Penalty function methods for constrained optimization with genetic algorithms." Mathematical and computational Applications 10.1 (2005): 45-56. 
[https://www.mdpi.com/2297-8747/10/1/45/pdf](https://www.mdpi.com/2297-8747/10/1/45/pdf)

This one is also interesting imho:

Schlüter, Martin, and Matthias Gerdts. "The oracle penalty method." Journal of Global Optimization 47.2 (2010): 293-325.
[https://www.researchgate.net/profile/Martin-Schlueter-3/publication/225199641_The_oracle_penalty_method/links/02e7e518750f5e3bcd000000/The-oracle-penalty-method.pdf](https://www.researchgate.net/profile/Martin-Schlueter-3/publication/225199641_The_oracle_penalty_method/links/02e7e518750f5e3bcd000000/The-oracle-penalty-method.pdf)

Good luck, and please report back if you try some different things out and they perform differently. Might help us decide what to support in the future.

**Comment by robertfeldt** [comment]
Actually, you can probably start with the latter, Schlüter paper since it also gives an overview of common penalty functions before introducing their new one.

**Comment by robertfeldt** [comment]
Note also that even though the experimental results of Schlüter does show some benefit in their new, relatively complex method the static penalty method that I alluded to above has fairly similar performance and is much easier. So I'd say there is some evidence for starting a static penalty like that. If you have a very high-dimensional problem though, then you might want to look for more complex and recent results in this space.

**Comment by robertfeldt** [comment]
I added another example of solving (a simple) contrained optimization problem, maybe this can be helpful to you:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/constrained_problem_with_inequalities.jl

**Comment by robertfeldt** [comment]
I also added a harder problem that also includes an equality constraint:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/constrained_problem_with_equality_and_inequalities.jl

**Comment by robertfeldt** [comment]
Note that in the latter problem the optimization finds the global optimum much quicker for lower values of the penalty constant so depending on your problem you can try to gradually reduce the size of K and see if you get different performance.

**Comment by gacarita** [comment]
Thank you. I'll check it out.
