### ISSUE TITLE
Getting errors/standard deviation from OptimizationResults object

### ISSUE THREAD

**Issue by astro-kevin** [robertfeldt/BlackBoxOptim.jl#213]
Is there a way to get the error/standard deviation of parameters from a OptimizationResults object?

**Comment by robertfeldt** [comment]
Standard deviation of what? In the parameter positions? If you are using a population-based optimizer it has a population of solutions so if you wanted you could get all those solutions and study the std over the parameters. But very unclear what the value would be since low std could just indicate that the population has converged to almost the same optimum. This might not say much about other optima. Can you describe more what you are trying to achieve?

**Comment by astro-kevin** [comment]
I guess what I'm looking for is the inverse of the hessian matrix returned by the fit because I'm fitting a negative log likelihood function, and that'll get me the gaussian approximation to the maximum likelihood. I know that such a thing exists in python packages which I used before, but I don't know if there's a way to get this here.

**Comment by astro-kevin** [comment]
Thanks, I guess I didn't understand how BlackBoxOptim worked.
