### ISSUE TITLE
MathProgBase Interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [robertfeldt/BlackBoxOptim.jl#59]
All of the JuliaOpt solvers (except surprisingly Optim.jl, but that should be remedied soon) have a MathProgBase interface. This makes it easy to swap between solvers in a code. However, currently one has to write a separate code just to use BlackBoxOptim.jl. Having a MathProgBase interface would fix this issue, and also make these methods accessible via JuMP.

**Comment by robertfeldt** [comment]
Yes, this has been discussed before and I'm positive. Do you happen to have some links with further details on MathProgBase and creating interfaces? Or do you have experience in writing such interfaces? I assume it would not be a major issue and I will look into it. Thanks.

**Comment by ChrisRackauckas** [comment]
I am not as familiar with MathProgBase as I am with other Julia interfaces, but I know it's documented here:

http://mathprogbasejl.readthedocs.io/en/latest/nlp.html

The Model type that it gives you has these functions implemented, and then you just model that into what you already have and it should work. You also need to create some kind of solver type to pass all of the options.

**Comment by robertfeldt** [comment]
Great, thanks. I will look more but it looks like you need to implement different Model types for different problems then. Hmm, it will actually not be trivial to support the non-linear one since there are many ways to map an optimization problem with multiple constraints so that it can be used with single-objective optimization algorithms. For our multi-objective ones it might be easier.

**Comment by robertfeldt** [comment]
Ok, I now realize only the non-linear one makes sense to use BlackBoxOptim for since the other, more structured ones should, at least in theory, always be faster to solve with more dedicated solvers. So at least there is some "focus" to the work when undertaken.

**Comment by robertfeldt** [comment]
Seems this can be modeled based on the NLOpt.jl MathProgBase interface here:
https://github.com/JuliaOpt/NLopt.jl/blob/master/src/NLoptSolverInterface.jl

I want to make sure we actually have compatible stop conditions in BlackBoxOptim before we "expose" this via MathProgBase. But it looks pretty straightforward otherwise.

**Comment by robertfeldt** [comment]
Seems an interface that is similar to https://github.com/SciML/GalacticOptim.jl might be the way to go? Will investigate going forward, the goal with BBO is slightly different though since we also want to support multi-objective optimization as well as exploration problems (and not only optimization problems), i.e. quality diversity problems. Closing this for now.
